"""skill added

Revision ID: a2b0d3ee863a
Revises: 
Create Date: 2024-03-16 17:04:38.907851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2b0d3ee863a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notetasklink')
    op.drop_table('note')
    op.drop_constraint('category_id_fkey', 'category', type_='foreignkey')
    op.add_column('labeltasklink', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labeltasklink', 'level')
    op.create_foreign_key('category_id_fkey', 'category', 'category', ['id'], ['id'])
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('note_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='note_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('notetasklink',
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name='notetasklink_note_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='notetasklink_task_id_fkey'),
    sa.PrimaryKeyConstraint('note_id', 'task_id', name='notetasklink_pkey')
    )
    # ### end Alembic commands ###
